#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/nextsession/nextsession /usr/bin/nextsession

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/nextsession.service ]; then
			rm /etc/systemd/system/nextsession.service /usr/lib/systemd/system/nextsession.service /usr/lib/systemd/user/nextsession.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/nextsession/files/systemd/nextsession.service /usr/lib/systemd/system/nextsession.service
		# try fix error in Ubuntu 18.04
		# Failed to reload nextsession.service: Unit nextsession.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/nextsession.service:10: Executable path is not absolute: pkill -f "nextsession --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/nextsession.service
		fi
		systemctl daemon-reload
		systemctl enable nextsession
		systemctl start nextsession
	fi
fi
